# קובץ docker-compose לפריסה מקומית
# זה מאפשר להריץ את האפליקציה עם Docker
# מסד הנתונים חייב להיות בענן (PostgreSQL)

version: '3.8'

services:
  # Web Application
  app:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OLLAMA_URL=http://ollama:11434
      - PORT=8080
    depends_on:
      - postgres
      - ollama
    networks:
      - app-network

  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - app-network

volumes:
  postgres_data:
  ollama_data:

networks:
  app-network:
    driver: bridge 