version: '3.8'

services:
  # שירות האפליקציה הראשי
  web:
    build: .
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/investments
      - OLLAMA_URL=http://ollama:11434
      - PORT=${PORT:-4000}
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this}
    depends_on:
      - db
      - ollama
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - app-network

  # מסד נתונים PostgreSQL
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=investments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - app-network

  # שירות Ollama עם מודל Llama3.1 8B
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    restart: unless-stopped
    command: >
      sh -c "
        echo '=== התחלת Ollama ===' &&
        ollama serve &
        sleep 15 &&
        echo '=== מוריד מודל llama3.1:8b ===' &&
        ollama pull llama3.1:8b &&
        echo '=== מודל llama3.1:8b מוכן! ===' &&
        wait
      "
    networks:
      - app-network

volumes:
  postgres_data:
  ollama_data:

networks:
  app-network:
    driver: bridge 