# קובץ docker-compose לפריסה מקומית
# זה מאפשר להריץ את האפליקציה עם Docker
# מסד הנתונים חייב להיות בענן (PostgreSQL)

version: '3.8'

services:
  # שירות 1: אפליקציית Flask
  flaskapp:
    build: .
    container_name: flaskapp
    environment:
      - DATABASE_URL=postgresql://postgres:WaPnQYjKJlhQJKCoNYbZxQRldTRJmTWW@shortline.proxy.rlwy.net:23148/railway
      - OLLAMA_URL=http://ollama:11434
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - ollama

  # שירות 2: מסד נתונים PostgreSQL
  postgres:
    image: postgres:15
    container_name: inv_db_Postgres
    environment:
      - POSTGRES_DB=investments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - investment-network
    restart: unless-stopped

  # שירות 3: שרת Ollama לבינה מלאכותית
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:

networks:
  investment-network:
    driver: bridge 