version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-local
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        ollama serve &
        sleep 10
        ollama pull llama3.1:8b
        wait

volumes:
  ollama_data:
    driver: local 