# קובץ docker-compose לפריסה מקומית
# זה מאפשר להריץ את האפליקציה עם Docker
# מסד הנתונים חייב להיות בענן (PostgreSQL)

version: '3.8'

services:
  # Web Application
  web:
    build: .
    container_name: tomer_portfolio_app
    restart: unless-stopped
    ports:
      - "${PORT:-4000}:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OLLAMA_URL=${OLLAMA_URL:-http://localhost:11434}
      - PORT=4000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - portfolio_network

  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: tomer_portfolio_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network

volumes:
  postgres_data:

networks:
  portfolio_network: 