services:
  - type: web
    name: investment-manager
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free 